site/src/main/java/com/cervisium/webapp/bean/AlbumManagerBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.entity.Album;

@ViewScoped
@Named("albumManager")
public class AlbumManagerBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private List<Album> albums;
	
	public List<Album> getAlbums() { return albums; }
	
	@PostConstruct
	public void init() {
		albums = em.createQuery("SELECT a FROM Album a WHERE a.brewery.id = :breweryId ORDER BY a.addedTime DESC", Album.class)
			.setParameter("breweryId", session.getActiveBrewery().getId()).getResultList();
	}
}

site/src/main/java/com/cervisium/webapp/bean/BrewersBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.log4j.Logger;
import org.mindrot.jbcrypt.BCrypt;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.bean.model.PasswordChange;
import com.cervisium.webapp.entity.Brewer;
import com.cervisium.webapp.entity.BreweryUser;

@Named("brewers")
@ViewScoped
public class BrewersBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient Logger log;
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private Brewer newBrewer = new Brewer();
	private List<Brewer> brewers;
	private Brewer editedBrewer;
	private Integer selectedEditBrewerId;
	private SelectItem noBrewerSelectedItem = new SelectItem(new Integer(-1), "Select Brewer...");
	
	private IntegerKeyedModel<BreweryUser> breweryUsers;
	private BreweryUser selectedBreweryUser;
	private BreweryUser newBreweryUser;
	private PasswordChange passwordChange;
	private PasswordChange newUserPassword;
	
	private UIComponent changeNewPasswordConfirm;
	private UIComponent newUserPasswordConfirm;
	
	@PostConstruct
	public void init() {
		loadBrewerList();
		selectedEditBrewerId = -1;
		loadBreweryUsersList();
		resetNewBreweryUser();
	}
	
	public Brewer getNewBrewer() {
		return newBrewer;
	}
	
	public List<Brewer> getBrewers() {
		return brewers;
	}
	
	public Brewer getEditedBrewer() {
		return editedBrewer;
	}
	
	public void setEditedBrewer(Brewer editedBrewer) {
		this.editedBrewer = editedBrewer;
	}
	
	public Integer getSelectedEditBrewerId() {
		return selectedEditBrewerId;
	}
	
	public void setSelectedEditBrewerId(Integer selectedEditBrewerId) {
		this.selectedEditBrewerId = selectedEditBrewerId;
		editedBrewer = em.find(Brewer.class, selectedEditBrewerId);
		em.detach(editedBrewer);
	}
	
	public List<SelectItem> getBrewersItems() {
		ArrayList<SelectItem> items = new ArrayList<SelectItem>();
		for (Brewer b : getBrewers()) { items.add(new SelectItem(b.getId(), b.getName())); }
		return items;
	}
	
	public SelectItem getNoBrewerSelectedItem() {
		return noBrewerSelectedItem;
	}
	
	public IntegerKeyedModel<BreweryUser> getBreweryUsers() {
		return breweryUsers;
	}
	
	public void setBreweryUsers(IntegerKeyedModel<BreweryUser> breweryUsers) {
		this.breweryUsers = breweryUsers;
	}
	
	public BreweryUser getSelectedBreweryUser() {
		return selectedBreweryUser;
	}
	
	public void setSelectedBreweryUser(BreweryUser selectedBreweryUser) {
		this.selectedBreweryUser = selectedBreweryUser;
	}
	
	public BreweryUser getNewBreweryUser() {
		return newBreweryUser;
	}
	
	public void setNewBreweryUser(BreweryUser newBreweryUser) {
		this.newBreweryUser = newBreweryUser;
	}
	
	public PasswordChange getPasswordChange() {
		return passwordChange;
	}
	
	public void setPasswordChange(PasswordChange passwordChange) {
		this.passwordChange = passwordChange;
	}
	
	public UIComponent getChangeNewPasswordConfirm() {
		return changeNewPasswordConfirm;
	}
	
	public void setChangeNewPasswordConfirm(UIComponent changeNewPasswordConfirm) {
		this.changeNewPasswordConfirm = changeNewPasswordConfirm;
	}
	
	public PasswordChange getNewUserPassword() {
		return newUserPassword;
	}
	
	public void setNewUserPassword(PasswordChange newUserPassword) {
		this.newUserPassword = newUserPassword;
	}
	
	public UIComponent getNewUserPasswordConfirm() {
		return newUserPasswordConfirm;
	}
	
	public void setNewUserPasswordConfirm(UIComponent newUserPasswordConfirm) {
		this.newUserPasswordConfirm = newUserPasswordConfirm;
	}
	
	public void saveNewBrewer() {
		if (getBrewersWritable() == false) { return; }
		
		newBrewer.setBreweryId(session.getActiveBrewery().getId());
		em.persist(newBrewer);
		em.detach(newBrewer);
		brewers.add(newBrewer);
		newBrewer = new Brewer();
	}
	
	public void updateBrewer() {
		if (getBrewersWritable() == false) { return; }
		
		if (editedBrewer != null && selectedEditBrewerId >= 0) { em.merge(editedBrewer); }
		loadBrewerList();
	}
	
	public void deleteBrewer() {
		if (getBrewersWritable() == false) { return; }
		
		if (selectedEditBrewerId >= 0) {
			int deleted = em.createQuery("DELETE FROM Brewer b WHERE b.id = :id")
				.setParameter("id", editedBrewer.getId()).executeUpdate();
			if (deleted > 0) { loadBrewerList(); }
		}
		selectedEditBrewerId = -1;
		editedBrewer = null;
	}
	
	public boolean getBrewersWritable() {
		if (session.getUserActiveBreweryMember()) { return true; }
		return false;
	}
	
	public boolean getBreweryUsersWritable() {
		if (session.getLoggedIn()) {
			if (session.getLoggedInUser().getPrivUserAdmin()) {
				return true;
			}
		}
		
		return false;
	}
	
	public void selectBreweryUser() {
		passwordChange = new PasswordChange();
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void changePassword() {
		if (getBreweryUsersWritable() == false) { return; }
		
		if (passwordChange.getNewPassword().equals(passwordChange.getNewPasswordConfirm()) == false) {
			FacesContext.getCurrentInstance().addMessage(changeNewPasswordConfirm.getClientId(),
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Must match New Password", null));
		} else {
			String newHash = BCrypt.hashpw(passwordChange.getNewPassword(), BCrypt.gensalt(12));
			em.createQuery("UPDATE BreweryUser bu SET bu.passHash = :newHash WHERE bu.id = :id")
				.setParameter("newHash", newHash).setParameter("id", selectedBreweryUser.getId())
				.executeUpdate();
			
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_INFO, "Password changed for " + selectedBreweryUser.getEmail(), null));
			
			passwordChange = new PasswordChange();
		}
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void createBreweryUser() {
		if (getBreweryUsersWritable() == false) { return; }
		
		if (newUserPassword.getNewPassword().equals(newUserPassword.getNewPasswordConfirm()) == false) {
			FacesContext.getCurrentInstance().addMessage(newUserPasswordConfirm.getClientId(),
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Must match New User Password", null));
		} else {
			newBreweryUser.setPassHash(BCrypt.hashpw(newUserPassword.getNewPassword(), BCrypt.gensalt(12)));
			newBreweryUser.setBrewery(session.getActiveBrewery());
			
			em.persist(newBreweryUser);
			em.detach(newBreweryUser);
			em.flush();
			
			loadBreweryUsersList();
			
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_INFO, "New brewery user created: " + newBreweryUser.getEmail(), null));
			
			newBreweryUser = new BreweryUser();
			newUserPassword = new PasswordChange();
		}
	}
	
	public void resetNewBreweryUser() {
		newBreweryUser = new BreweryUser();
		newUserPassword = new PasswordChange();
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void deleteSelectedUser() {
		if (getBreweryUsersWritable() == false) { return; }
		
		if (selectedBreweryUser == null) {
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Delete requested but no user is selected", null));
		} else {
			em.createQuery("DELETE FROM BreweryUser bu WHERE bu.id = :id")
				.setParameter("id", selectedBreweryUser.getId()).executeUpdate();
			
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_INFO, "Brewery User deleted: " + selectedBreweryUser.getEmail(), null));
			
			selectedBreweryUser = null;
			
			loadBreweryUsersList();
		}
	}
	
	protected void loadBreweryUsersList() {
		List<BreweryUser> users = em.createQuery("SELECT bu FROM BreweryUser bu WHERE bu.brewery.id = :breweryId", BreweryUser.class)
			.setParameter("breweryId", session.getActiveBrewery().getId()).getResultList();
		for (BreweryUser bu : users) { em.detach(bu); bu.setPassHash(null); }
		breweryUsers = new IntegerKeyedModel<BreweryUser>(users);
	}
	
	protected void loadBrewerList() {
		brewers = em.createQuery("SELECT b FROM Brewer b WHERE b.breweryId = :breweryId", Brewer.class)
			.setParameter("breweryId", session.getActiveBrewery().getId())
			.getResultList();
	}
}

site/src/main/java/com/cervisium/webapp/bean/InventoryBean.java
package com.cervisium.webapp.bean;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.joda.time.DateTime;
import org.joda.time.Days;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.InventoryItem;
import com.cervisium.webapp.entity.Brewing;

@Named("inventory")
@RequestScoped
public class InventoryBean {

	@Inject @Cervisium private EntityManager em;

	private ArrayList<InventoryItem> inventoryItems;
	
	public ArrayList<InventoryItem> getInventoryItems() {
		return inventoryItems;
	}
	
	public void setInventoryItems(ArrayList<InventoryItem> inventoryItems) {
		this.inventoryItems = inventoryItems;
	}
	
	@PostConstruct
	public void init() {
		inventoryItems = new ArrayList<InventoryItem>();
		
		List<Brewing> brewings = em.createQuery("SELECT b FROM Brewing b where dateFinish = NULL", Brewing.class)
			.getResultList();
		
		for (Brewing brewing : brewings) {
			InventoryItem item = new InventoryItem();
			item.setName(brewing.getFormulation().getRecipe().getName() + " - " + brewing.getFormulation().getName());
			item.setBrewingId(brewing.getId());
			item.setDateBrew(brewing.getDateBrew());
			item.setDateSecondary(brewing.getDateSecondary());
			item.setDateKeg(brewing.getDateKeg());
			item.setDateBottle(brewing.getDateBottle());
			item.setStage(brewing.getBrewStage());
			
			Days age = Days.daysBetween(new DateTime(brewing.getDateBrew()), new DateTime());
			item.setAgeDays(age.getDays());
			
			inventoryItems.add(item);
		}
		
		Collections.sort(inventoryItems);
	}
}

site/src/main/java/com/cervisium/webapp/bean/NewsBean.java
package com.cervisium.webapp.bean;

import java.util.List;

import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.entity.NewsItem;

@RequestScoped
@Named("news")
public class NewsBean {

	@Inject @Cervisium private EntityManager em;
	@Inject private SessionState session;
	
	private List<NewsItem> newsItems;
	private Integer offset;
	private Integer nextOffset;
	private Boolean renderMoreLink = Boolean.FALSE;
	
	public List<NewsItem> getNewsItems() { return newsItems; }
	public void setNewsItems(List<NewsItem> newsItems) { this.newsItems = newsItems; }
	public Integer getOffset() { return offset; }
	public void setOffset(Integer offset) { this.offset = offset; }
	public Integer getNextOffset() { return nextOffset; }
	public void setNextOffset(Integer nextOffset) { this.nextOffset = nextOffset; }
	public Boolean getRenderMoreLink() { return renderMoreLink; }
	public void setRenderMoreLink(Boolean renderMoreLink) { this.renderMoreLink = renderMoreLink; }
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void loadNewsItems() {
		if (offset == null) { offset = 0; }
		
		newsItems = em.createQuery("SELECT ni FROM NewsItem ni WHERE ni.breweryId = :breweryId " +
			"ORDER BY ni.postDate DESC", NewsItem.class)
			.setParameter("breweryId", session.getActiveBrewery().getId())
			.setFirstResult(offset).setMaxResults(10).getResultList();
		
		nextOffset = offset + 10;
		
		if (newsItems.size() == 10) { renderMoreLink = Boolean.TRUE; }
	}
}

site/src/main/java/com/cervisium/webapp/bean/SessionState.java
package com.cervisium.webapp.bean;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.log4j.Logger;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.entity.Brewery;
import com.cervisium.webapp.entity.BreweryUser;

@Named("sessionState")
@SessionScoped
public class SessionState implements Serializable {
	public static final long serialVersionUID = 1l;

	@Inject @Cervisium private transient Logger log;
	@Inject @Cervisium private transient EntityManager em;
	
	private BreweryUser loggedInUser;
	private Brewery activeBrewery;
	
	@PostConstruct
	public void init() {
		activeBrewery = em.createQuery("SELECT b FROM Brewery b WHERE b.name = :name", Brewery.class)
			.setParameter("name", "Cervisium")
			.getSingleResult();
		if (activeBrewery != null) {
			log.info("Loaded default brewery: " + activeBrewery.getName());
		} else {
			log.error("Failed to find default brewery Cervisium");
		}
		
		loggedInUser = null;
	}
	
	public Brewery getActiveBrewery() {
		return activeBrewery;
	}
	
	public void setActiveBrewery(Brewery activeBrewery) {
		this.activeBrewery = activeBrewery;
	}

	public boolean getLoggedIn() {
		return (loggedInUser != null);
	}
	
	public BreweryUser getLoggedInUser() {
		return loggedInUser;
	}
	
	public void setLoggedInUser(BreweryUser loggedInUser) {
		this.loggedInUser = loggedInUser;
	}
	
	public boolean getUserActiveBreweryMember() {
		if (getLoggedIn()) {
			if (getLoggedInUser().getBrewery().getId() == getActiveBrewery().getId()) {
				return true;
			}
		}
		
		return false;
	}
}

site/src/main/java/com/cervisium/webapp/bean/model/InventoryItem.java
package com.cervisium.webapp.bean.model;

import java.util.Date;

import com.cervisium.webapp.entity.BrewStage;

public class InventoryItem implements Comparable<InventoryItem> {

	private String name;
	private Integer brewingId;
	private Date dateBrew;
	private Date dateSecondary;
	private Date dateKeg;
	private Date dateBottle;
	private BrewStage stage;
	private Integer ageDays;
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Integer getBrewingId() {
		return brewingId;
	}
	
	public void setBrewingId(Integer brewingId) {
		this.brewingId = brewingId;
	}
	
	public Date getDateBrew() {
		return dateBrew;
	}
	
	public void setDateBrew(Date dateBrew) {
		this.dateBrew = dateBrew;
	}
	
	public Date getDateSecondary() {
		return dateSecondary;
	}
	
	public void setDateSecondary(Date dateSecondary) {
		this.dateSecondary = dateSecondary;
	}
	
	public Date getDateKeg() {
		return dateKeg;
	}
	
	public void setDateKeg(Date dateKeg) {
		this.dateKeg = dateKeg;
	}
	
	public Date getDateBottle() {
		return dateBottle;
	}
	
	public void setDateBottle(Date dateBottle) {
		this.dateBottle = dateBottle;
	}
	
	public BrewStage getStage() {
		return stage;
	}
	
	public void setStage(BrewStage stage) {
		this.stage = stage;
	}
	
	public Integer getAgeDays() {
		return ageDays;
	}
	
	public void setAgeDays(Integer ageDays) {
		this.ageDays = ageDays;
	}
	
	public String getImageFile() {
		switch (stage) {
			case PRIMARY: return "6carb.png";
			case SECONDARY: return "5carb.png";
			case KEG: return "keg.png";
			default: return "bottle.png";
		}
	}
	
	@Override
	public int compareTo(InventoryItem o) {
		int myPts = getStage().getOrderPoints();
		int oPts = o.getStage().getOrderPoints();
		
		if (getDateBrew().before(o.getDateBrew())) { oPts += 1; }
		else if (getDateBrew().after(o.getDateBrew())) { myPts += 1; }
		
		return oPts - myPts;
	}
}

site/src/main/webapp/auth.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">

<body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="body">
			<p:outputPanel id="authPanel">
				<h:form id="authForm" prependId="false" binding="#{auth.authForm}">
					<ui:fragment rendered="#{sessionState.loggedIn == false}">
						<h2>Cervisium Login</h2>
						<p:messages id="authFormMessages" for="authForm" showDetail="false" />
						<p:panel>
							<h:panelGrid columns="3" cellspacing="3" style="margin-bottom:16px;">
								<p:outputLabel for="email" value="Email: " />
								<p:inputText id="email" value="#{auth.email}" style="width:400px;" />
								<p:message for="email" />
								
								<p:outputLabel for="password" value="Password: " />
								<p:password id="password" value="#{auth.password}" style="width:400px;" />
								<p:message for="password" />
							</h:panelGrid>
							
							<p:commandButton id="loginButton" value="Login" action="#{auth.login}" update=":authPanel, :userPanelOutput" />
						</p:panel>
					</ui:fragment>
				</h:form>
				
					
				<ui:fragment rendered="#{sessionState.loggedIn == true}">
					<div class="biggerText"><p>You are logged in as <h:outputText value="#{sessionState.loggedInUser.email}" /></p></div>
					<h:form id="logoutForm" prependId="false">
						<div style="margin-bottom:16px;">
							<p:commandButton id="logoutButton" value="Logout" action="#{auth.logout}" update=":authPanel, :userPanelOutput" />
						</div>
					</h:form>
					
					<h:form id="passwordChangeForm" prependId="false" binding="#{auth.passwordChangeForm}">
						<p:messages id="passwordChangeMessages" for="passwordChangeForm" />
						<p:panel id="changePasswordPanel" header="Change Password">
							<h:panelGrid columns="3" cellspacing="3" style="margin-bottom:16px;">
								<p:outputLabel for="oldPassword" value="Current Password: " />
								<p:password id="oldPassword" value="#{auth.passwordChange.oldPassword}" style="width:300px;" />
								<p:message for="oldPassword" />
								
								<p:outputLabel for="newPassword" value="New Password: " />
								<p:password id="newPassword" value="#{auth.passwordChange.newPassword}" style="width:300px;" />
								<p:message for="newPassword" />
								
								<p:outputLabel for="newPasswordConfirm" value="New Password (again): " />
								<p:password id="newPasswordConfirm" value="#{auth.passwordChange.newPasswordConfirm}"
									style="width:300px;" binding="#{auth.newPasswordConfirm}" />
								<p:message for="newPasswordConfirm" />
							</h:panelGrid>
							
							<p:commandButton id="changePasswordButton" value="Change Password" action="#{auth.changePassword}" update=":authPanel"
								style="margin-right:8px;" />
							<p:commandButton id="cancelChangePasswordButton" value="Cancel" action="#{auth.cancelChangePassword}" update="@form" />
						</p:panel>
					</h:form>
				</ui:fragment>
			</p:outputPanel>
		</ui:define>
	</ui:composition>
</body>
</html>

site/src/main/webapp/inventory.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">
<body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="body">
			<h:outputStylesheet library="css" name="inventory.css" />
			<h2>Inventory</h2>
			
			<ui:repeat var="item" value="#{inventory.inventoryItems}">
				<div class="invItem">
					<div class="invItemImg">
						<h:graphicImage library="img" name="#{item.imageFile}" />
					</div>
					<div class="invItemDetail">
						<h:link outcome="/recipes/brewings/edit">
							<f:param name="id" value="#{item.brewingId}" />
							<h3><h:outputText value="#{item.name}" /></h3>
						</h:link>
						<p>Age: <h:outputText value="#{item.ageDays}" /> days - 
						Current Stage: <h:outputText value="#{item.stage.stageName}" /></p>
						<p:panelGrid columns="4" styleClass="invItemTable">
							<h:outputLabel value="Brew Date:" />
							<h:outputText value="#{item.dateBrew}" />
							<h:outputLabel value="Secondary Date:" />
							<h:outputText value="#{item.dateSecondary}" />
							<h:outputLabel value="Keg Date:" />
							<h:outputText value="#{item.dateKeg}" />
							<h:outputLabel value="Bottle Date:" />
							<h:outputText value="#{item.dateBottle}" />
						</p:panelGrid>
					</div>
					<div style="clear:both;"></div>
				</div>
			</ui:repeat>
		</ui:define>
	</ui:composition>
</body>
</html>

site/src/main/webapp/mobile.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pm="http://primefaces.org/mobile"
	contentType="text/html"
	renderKitId="PRIMEFACES_MOBILE">
	
	<pm:page title="Cervisium">
		<pm:view id="main">
			<pm:header title="Cervisium" />
			<pm:content>
				<p style="padding-bottom:16px;">Welcome to the Cervisium brewery! Select a section from the links below:</p>
				<p:dataList>
					<h:outputLink value="#recipeList">Recipe List</h:outputLink>
				</p:dataList>
			</pm:content>
		</pm:view>
		
		<pm:view id="recipeList">
			<pm:header title="Recipe List">
				<f:facet name="left"><p:button value="Back" icon="back" href="#main?reverse=true"/></f:facet>
			</pm:header>
			<pm:content>
				<p:dataList value="#{recipeList.recipes}" var="recipe">
					<h:outputText value="#{recipe.name}" />
				</p:dataList>
			</pm:content>
		</pm:view>
	</pm:page>
</f:view>