site/src/main/java/com/cervisium/webapp/bean/AlbumEditorBean.java
package com.cervisium.webapp.bean;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;

import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.FilenameUtils;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.PhotoFileException;
import com.cervisium.webapp.PhotoFileLocation;
import com.cervisium.webapp.Resources;
import com.cervisium.webapp.entity.Album;
import com.cervisium.webapp.entity.Photo;
import com.cervisium.webapp.services.ImageService;
import com.cervisium.webapp.services.PhotoDeleteService;

@ViewScoped
@Named("albumEditor")
public class AlbumEditorBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject @Cervisium private transient Logger log;
	@Inject private SessionState session;
	@Inject @PhotoFileLocation File photoFileLocation;
	
	@Inject private transient ImageService imageService;
	@Inject private transient PhotoDeleteService deleteService;
	
	private Integer editAlbumId;
	private Album editedAlbum;
	private String selectedPhotoIdStr;
	private Photo selectedPhoto;
	private Integer resizeMaxDim;
	
	public Integer getEditAlbumId() { return editAlbumId; }
	public void setEditAlbumId(Integer editAlbumId) { this.editAlbumId = editAlbumId; }
	public Album getEditedAlbum() { return editedAlbum; }
	public void setEditedAlbum(Album editedAlbum) { this.editedAlbum = editedAlbum; }
	public String getSelectedPhotoIdStr() { return selectedPhotoIdStr; }
	public void setSelectedPhotoIdStr(String selectedPhotoIdStr) { this.selectedPhotoIdStr = selectedPhotoIdStr; }
	public Photo getSelectedPhoto() { return selectedPhoto; }
	public void setSelectedPhoto(Photo selectedPhoto) { this.selectedPhoto = selectedPhoto; }
	public Integer getResizeMaxDim() { return resizeMaxDim; }
	public void setResizeMaxDim(Integer resizeMaxDim) { this.resizeMaxDim = resizeMaxDim; }
	
	public String getPhotoURLPrefix() {
		return Resources.getPhotoURLPrefix();
	}
	
	public void loadAlbum() {
		if (editAlbumId < 0) {
			editedAlbum = new Album();
			editedAlbum.setBrewery(session.getActiveBrewery());
		} else {
			editedAlbum = em.find(Album.class, editAlbumId);
		}
		
		selectedPhotoIdStr = null;
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void saveAlbum() throws PhotoFileException {
		if (getWritable() == false) { return; }
		
		boolean newAlbum = false;
		
		if (editedAlbum.getId() == null) {
			newAlbum = true;
			
			editedAlbum.generateFolderName();
			em.persist(editedAlbum);
			em.flush();
			editedAlbum.generateFolderName();
			em.flush();
			
			File newAlbumFolder = new File(photoFileLocation, editedAlbum.getFolder());
			if (newAlbumFolder.isDirectory() == false) { 
				newAlbumFolder.mkdir();
			}
			
			if (newAlbumFolder.isDirectory() == false) {
				String err = "Failed to create album directory: " + newAlbumFolder.getAbsolutePath();
				log.error(err);
				throw new PhotoFileException(err);
			}
			
			em.detach(editedAlbum);
		} else {
			em.merge(editedAlbum);
		}
		
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo album details saved.", null));
		
		if (newAlbum) { Navigation.navigate("/photo/album?faces-redirect=true&id=" + Integer.toString(editedAlbum.getId())); }
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void fileUploadListener(FileUploadEvent event) throws PhotoFileException {
		if (editedAlbum.getId() == null || getWritable() == false) { return; }
		
		// Prepare a record for the new photo
		Photo photo = new Photo();
		photo.setAlbum(editedAlbum);
		photo.setPhotoTime(new Date());
		
		String newFileName = FilenameUtils.simplifyFilename(event.getFile().getFileName());
		photo.setFileName(newFileName);
		
		File albumFolder = new File(photoFileLocation, editedAlbum.getFolder());
		File photoFile = new File(albumFolder, newFileName);
		FileOutputStream photoOut = null;
		
		try {
			photoOut = new FileOutputStream(photoFile);
			IOUtils.copy(event.getFile().getInputstream(), photoOut);
		} catch (IOException ioe) {
			String err = "Failed to save photo file: " + photoFile.getAbsolutePath();
			log.error(err, ioe);
			throw new PhotoFileException(err, ioe);
		} finally {
			if (photoOut != null) { try { photoOut.close(); } catch (IOException ioe2) {} }
		}
		
		// File saved okay, persist the photo
		em.persist(photo);
		em.flush();
		
		imageService.generateThumb(photo);
		
		loadAlbum();
	}
	
	public void rethumbAlbum() {
		if (getWritable() == false) { return; }
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Initiated background regeneration of thumbnails.", null));
		imageService.rethumbAlbum(editedAlbum);
	}
	
	public void photoClickListener() {
		Integer selectedPhotoId = Integer.parseInt(selectedPhotoIdStr);
		selectedPhoto = em.find(Photo.class, selectedPhotoId);
	}
	
	public void saveSelectedPhoto() {
		if (getWritable() == false) { return; }
		em.merge(selectedPhoto);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo saved.", null));
	}
	
	public void resizeSelectedPhoto() {
		if (getWritable() == false) { return; }
		if (resizeMaxDim == null || resizeMaxDim < 100) {
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Resize max dimension too small, must be greater than 100", null));
			return;
		}
		
		imageService.resizePhoto(selectedPhoto, resizeMaxDim);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo resized.", null));
	}
	
	public void deleteSelectedPhoto() {
		if (getWritable() == false) { return; }
		deleteService.deletePhoto(selectedPhoto);
		loadAlbum();
	}
	
	public String deleteAlbum() {
		if (getWritable() == false) { return ""; }
		deleteService.deleteAlbum(editedAlbum);
		return "/photo/manage?faces-redirect=true";
	}
	
	public boolean getWritable() {
		if (session.getLoggedIn() == false || session.getLoggedInUser().getPrivManagePhotos() == false) { return false; }
		if (editedAlbum.getBrewery().getId() != session.getLoggedInUser().getBrewery().getId()) { return false; }
		
		return true;
	}
}

site/src/main/java/com/cervisium/webapp/entity/Brewing.java
package com.cervisium.webapp.entity;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.cervisium.webapp.FilenameUtils;

@Entity
@Table(name = "BREWING")
public class Brewing implements IntegerKeyedEntity {

	private Integer id;
	private Formulation formulation;
	private Date dateBrew;
	private Date dateSecondary;
	private Date dateKeg;
	private Date dateBottle;
	private Date dateFinish;
	private Float og;
	private Float fg;
	private Float mashTempF;
	private Float efficiency;
	private Float attenuationApp;
	private Float attenuationReal;
	private Integer ibu;
	private Integer srm;
	private Float abv;
	private Integer calsPint;
	
	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "FORMULATION_ID", referencedColumnName = "ID", nullable = false)
	public Formulation getFormulation() {
		return formulation;
	}

	public void setFormulation(Formulation formulation) {
		this.formulation = formulation;
	}

	@Column(name = "DATE_BREW")
	@Temporal(TemporalType.DATE)
	@NotNull(message = "A brew date must be specified")
	public Date getDateBrew() {
		return dateBrew;
	}

	public void setDateBrew(Date dateBrew) {
		this.dateBrew = dateBrew;
	}

	@Column(name = "DATE_SECONDARY")
	@Temporal(TemporalType.DATE)
	public Date getDateSecondary() {
		return dateSecondary;
	}

	public void setDateSecondary(Date dateSecondary) {
		this.dateSecondary = dateSecondary;
	}

	@Column(name = "DATE_KEG")
	@Temporal(TemporalType.DATE)
	public Date getDateKeg() {
		return dateKeg;
	}

	public void setDateKeg(Date dateKeg) {
		this.dateKeg = dateKeg;
	}

	@Column(name = "DATE_BOTTLE")
	@Temporal(TemporalType.DATE)
	public Date getDateBottle() {
		return dateBottle;
	}

	public void setDateBottle(Date dateBottle) {
		this.dateBottle = dateBottle;
	}

	@Column(name = "DATE_FINISH")
	@Temporal(TemporalType.DATE)
	public Date getDateFinish() {
		return dateFinish;
	}

	public void setDateFinish(Date dateFinish) {
		this.dateFinish = dateFinish;
	}

	@Column(name = "OG")
	public Float getOg() {
		return og;
	}

	public void setOg(Float og) {
		this.og = og;
	}

	@Column(name = "FG")
	public Float getFg() {
		return fg;
	}

	public void setFg(Float fg) {
		this.fg = fg;
	}

	@Column(name = "MASH_TEMP_F")
	public Float getMashTempF() {
		return mashTempF;
	}

	public void setMashTempF(Float mashTempF) {
		this.mashTempF = mashTempF;
	}

	@Column(name = "EFFICIENCY")
	public Float getEfficiency() {
		return efficiency;
	}

	public void setEfficiency(Float efficiency) {
		this.efficiency = efficiency;
	}
	
	@Transient
	public Float getEfficiencyPct() {
		return efficiency == null ? null : Math.round(efficiency * 1000) / 10f;
	}
	
	public void setEfficiencyPct(Float efficiencyPct) {
		efficiency = efficiencyPct / 100f;
	}
	
	@Column(name = "ATTENUATION_APP")
	public Float getAttenuationApp() {
		return attenuationApp;
	}

	public void setAttenuationApp(Float attenuationApp) {
		this.attenuationApp = attenuationApp;
	}
	
	@Transient
	public Float getAttenuationAppPct() {
		return attenuationApp == null ? null : Math.round(attenuationApp * 1000) / 10f;
	}

	public void setAttenuationAppPct(Float attenuationAppPct) {
		this.attenuationApp = attenuationAppPct / 100f;
	}

	@Column(name = "ATTENUATION_REAL")
	public Float getAttenuationReal() {
		return attenuationReal;
	}

	public void setAttenuationReal(Float attenuationReal) {
		this.attenuationReal = attenuationReal;
	}
	
	@Transient
	public Float getAttenuationRealPct() {
		return attenuationReal == null ? null : Math.round(attenuationReal * 1000) / 10f;
	}

	public void setAttenuationRealPct(Float attenuationRealPct) {
		this.attenuationReal = attenuationRealPct / 100f;
	}

	@Column(name = "IBU")
	public Integer getIbu() {
		return ibu;
	}

	public void setIbu(Integer ibu) {
		this.ibu = ibu;
	}

	@Column(name = "SRM")
	public Integer getSrm() {
		return srm;
	}

	public void setSrm(Integer srm) {
		this.srm = srm;
	}

	@Column(name = "ABV")
	public Float getAbv() {
		return abv;
	}

	public void setAbv(Float abv) {
		this.abv = abv;
	}
	
	@Transient
	public Float getAbvPct() {
		return abv == null ? null : Math.round(abv * 1000) / 10f;
	}

	public void setAbvPct(Float abvPct) {
		this.abv = abvPct / 100f;
	}

	@Column(name = "CALS_PINT")
	public Integer getCalsPint() {
		return calsPint;
	}

	public void setCalsPint(Integer calsPint) {
		this.calsPint = calsPint;
	}
	
	@Transient
	public BrewStage getBrewStage() {
		if (dateFinish == null) {
			if (dateBottle == null) {
				if (dateKeg == null) {
					if (dateSecondary == null) {
						return BrewStage.PRIMARY;
					} else {
						return BrewStage.SECONDARY;
					}
				} else {
					return BrewStage.KEG;
				}
			} else {
				return BrewStage.BOTTLES;
			}
		} else {
			return BrewStage.FINISHED;
		}
	}
	
	@Transient @JsonIgnore
	public String getFriendlyName() {
		Format formatter = new SimpleDateFormat("yyyy-MM-dd");
		String friendlyName = formulation.getRecipe().getName() + "-" + formulation.getName() + "_" +
			formatter.format(getDateBrew());
		return FilenameUtils.simplifyFilename(friendlyName);
	}
}

site/src/main/java/com/cervisium/webapp/entity/Recipe.java
package com.cervisium.webapp.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "RECIPE")
public class Recipe implements IntegerKeyedEntity {

	private Integer id;
	private Integer breweryId;
	private String name;
	private String slugName;
	private String style;
	private Float targetOg;
	private Float targetFg;
	private Integer targetIBU;
	private Integer targetSRM;
	private Integer referenceVersion;
	private List<Brewer> authors = new ArrayList<Brewer>();
	private List<Formulation> formulations = new ArrayList<Formulation>();
	
	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "BREWERY_ID")
	@NotNull
	public Integer getBreweryId() {
		return breweryId;
	}

	public void setBreweryId(Integer breweryId) {
		this.breweryId = breweryId;
	}
	
	@Column(name = "NAME")
	@NotNull
	@Size(min = 1, max = 255)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SLUG_NAME")
	public String getSlugName() {
		return slugName;
	}

	public void setSlugName(String slugName) {
		this.slugName = slugName;
	}

	@Column(name = "STYLE")
	@NotNull
	@Size(min = 1, max = 255)
	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Column(name = "TARGET_OG")
	@NotNull
	public Float getTargetOg() {
		return targetOg;
	}

	public void setTargetOg(Float targetOg) {
		this.targetOg = targetOg;
	}
	
	@Column(name = "TARGET_FG")
	@NotNull
	public Float getTargetFg() {
		return targetFg;
	}

	public void setTargetFg(Float targetFg) {
		this.targetFg = targetFg;
	}

	@Column(name = "TARGET_IBU")
	@NotNull
	public Integer getTargetIBU() {
		return targetIBU;
	}

	public void setTargetIBU(Integer targetIBU) {
		this.targetIBU = targetIBU;
	}

	@Column(name = "TARGET_SRM")
	@NotNull
	public Integer getTargetSRM() {
		return targetSRM;
	}

	public void setTargetSRM(Integer targetSRM) {
		this.targetSRM = targetSRM;
	}

	@Column(name = "REFERENCE_VERSION")
	public Integer getReferenceVersion() {
		return referenceVersion;
	}

	public void setReferenceVersion(Integer referenceVersion) {
		this.referenceVersion = referenceVersion;
	}
	
	@ManyToMany(cascade = { CascadeType.REFRESH }, fetch = FetchType.LAZY)
	@JoinTable(name = "RECIPE_AUTHOR_MAPPING",
		joinColumns = @JoinColumn(name = "RECIPE_ID", referencedColumnName = "ID"),
		inverseJoinColumns = @JoinColumn(name = "BREWER_ID", referencedColumnName = "ID"))
	public List<Brewer> getAuthors() {
		return authors;
	}
	
	public void setAuthors(List<Brewer> authors) {
		this.authors = authors;
	}
	
	@OneToMany(mappedBy = "recipe", cascade = { CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH })
	public List<Formulation> getFormulations() {
		return formulations;
	}
	
	public void setFormulations(List<Formulation> formulations) {
		this.formulations = formulations;
	}
}

site/src/main/webapp/recipes/brewings/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">

<body>
	<ui:composition template="/templates/template.xhtml">
		<f:metadata>
			<f:viewParam name="id" value="#{brewingEditor.editBrewingId}" />
			<s:viewAction action="#{brewingEditor.loadBrewing}" />
		</f:metadata>
		
		<ui:define name="body">
			<style type="text/css">
				.inpSize { width: 180px; }
			</style>
		
		
			<h:link styleClass="breadcrumbLink" outcome="/recipes/formulation?faces-redirect=true" >
				&lt;- Back To <h:outputText value="#{brewingEditor.editedBrewing.formulation.recipe.name}" /> -
				<h:outputText value="#{brewingEditor.editedBrewing.formulation.name}" />
				<f:param name="id" value="#{brewingEditor.editedBrewing.formulation.id}" />
			</h:link>
			<p:panel id="editBrewingPanel" header="Edit Brewing">
				<h:form id="editBrewingForm" prependId="false">
					<h3>
						Brewing of
						<h:outputText value="#{brewingEditor.editedBrewing.formulation.recipe.name}" /> -
						<h:outputText value="#{brewingEditor.editedBrewing.formulation.name}" />
					</h3>
					
					<h4>Stage: <h:outputText value="#{brewingEditor.editedBrewing.brewStage.stageName}" /></h4>
					
					<h:panelGrid columns="3" cellpadding="3" style="margin-bottom:16px;">
						<p:outputLabel for="dateBrew" value="Brew Date: " />
						<p:calendar id="dateBrew" mode="popup" value="#{brewingEditor.editedBrewing.dateBrew}"
							pattern="yyyy-MM-dd" readonlyInput="true" navigator="true" styleClass="inpSize"
							readonly="#{brewingEditor.writable == false}" />
						<p:message for="dateBrew" />
						
						<p:outputLabel for="dateSecondary" value="Secondary Date: " />
						<p:calendar id="dateSecondary" mode="popup" value="#{brewingEditor.editedBrewing.dateSecondary}"
							pattern="yyyy-MM-dd" readonlyInput="false" navigator="true" styleClass="inpSize"
							readonly="#{brewingEditor.writable == false}" />
						<p:message for="dateSecondary" />
						
						<p:outputLabel for="dateKeg" value="Keg Date: " />
						<p:calendar id="dateKeg" mode="popup" value="#{brewingEditor.editedBrewing.dateKeg}"
							pattern="yyyy-MM-dd" readonlyInput="false" navigator="true" styleClass="inpSize"
							readonly="#{brewingEditor.writable == false}" />
						<p:message for="dateKeg" />
						
						<p:outputLabel for="dateBottle" value="Bottle Date: " />
						<p:calendar id="dateBottle" mode="popup" value="#{brewingEditor.editedBrewing.dateBottle}"
							pattern="yyyy-MM-dd" readonlyInput="false" navigator="true" styleClass="inpSize"
							readonly="#{brewingEditor.writable == false}" />
						<p:message for="dateBottle" />
						
						<p:outputLabel for="dateFinish" value="Finish Date: " />
						<p:calendar id="dateFinish" mode="popup" value="#{brewingEditor.editedBrewing.dateFinish}"
							pattern="yyyy-MM-dd" readonlyInput="false" navigator="true" styleClass="inpSize"
							readonly="#{brewingEditor.writable == false}" />
						<p:message for="dateFinish" />
					</h:panelGrid>
					<h:panelGrid columns="6" cellpadding="3" style="margin-bottom:16px;">
						<p:outputLabel for="mashTempF" value="Mash Temp (°F): " />
						<p:inputText id="mashTempF" value="#{brewingEditor.editedBrewing.mashTempF}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="mashTempF" />
						
						<p:outputLabel for="og" value="Original Gravity: " />
						<p:inputText id="og" value="#{brewingEditor.editedBrewing.og}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="og" />
						
						<p:outputLabel for="fg" value="Final Gravity: " />
						<p:inputText id="fg" value="#{brewingEditor.editedBrewing.fg}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="fg" />
						
						<p:outputLabel for="efficiency" value="Efficiency (%): " />
						<p:inputText id="efficiency" value="#{brewingEditor.editedBrewing.efficiencyPct}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="efficiency" />
						
						<p:outputLabel for="attenuationApp" value="App. Attenuation (%): " />
						<p:inputText id="attenuationApp" value="#{brewingEditor.editedBrewing.attenuationAppPct}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="attenuationApp" />
						
						<p:outputLabel for="attenuationReal" value="Real Attenuation (%): " />
						<p:inputText id="attenuationReal" value="#{brewingEditor.editedBrewing.attenuationRealPct}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="attenuationReal" />
						
						<p:outputLabel for="ibu" value="IBU: " />
						<p:inputText id="ibu" value="#{brewingEditor.editedBrewing.ibu}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="ibu" />
						
						<p:outputLabel for="srm" value="SRM: " />
						<p:inputText id="srm" value="#{brewingEditor.editedBrewing.srm}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="srm" />
						
						<p:outputLabel for="abv" value="Alc. By Volume (%): " />
						<p:inputText id="abv" value="#{brewingEditor.editedBrewing.abvPct}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="abv" />
						
						<p:outputLabel for="calsPint" value="Cals / Pint: " />
						<p:inputText id="calsPint" value="#{brewingEditor.editedBrewing.calsPint}" styleClass="inpSize"
							 readonly="#{brewingEditor.writable == false}" />
						<p:message for="calsPint" />
					</h:panelGrid>
					
					<p>Brew Notes:</p>
					<p:inputTextarea id="brewNotes" value="#{brewingEditor.brewingNotes.brewNotes}" style="width:850px;height:130px;margin-bottom:8px;"
						readonly="#{brewingEditor.writable == false}" autoResize="false" />
						
					<p>Taste Notes:</p>
					<p:inputTextarea id="tasteNotes" value="#{brewingEditor.brewingNotes.tasteNotes}" style="width:850px;height:130px;margin-bottom:16px;"
						readonly="#{brewingEditor.writable == false}" autoResize="false" />
					
					<ui:fragment rendered="#{brewingEditor.writable}">
						<p:commandButton id="saveBrewingButton" value="Save Brewing" action="#{brewingEditor.saveBrewing}" update="@form" style="margin-right:8px;"/>
						<p:commandButton id="refreshBrewingButton" value="Revert Changes" action="#{brewingEditor.refreshBrewing}" update="@form" style="margin-right:8px;" />
						<p:commandButton id="deleteButton" value="Delete Brewing" type="button" onclick="confirmDeleteDialog.show()" />
					</ui:fragment>
					
					<h3>BeerTools Data File</h3>
					<p:outputPanel id="dataFilePanel">
						<h:outputText value="No BeerTools file associated with this brewing." rendered="#{brewingEditor.brewingFileExists == false}"/>
						<h:outputLink value="/site/downloadRecipe/brewing?id=#{brewingEditor.editedBrewing.id}"
							rendered="#{brewingEditor.brewingFileExists == true}">
							Download BeerTools File
						</h:outputLink>
					</p:outputPanel>
					
					<ui:fragment rendered="#{brewingEditor.writable}">
						<h3>Upload BeerTools File</h3>
						<p>If you choose to import values from the uploaded BeerTools file, those
						values will replace any you have entered manually.</p>
						<h:panelGrid columns="2" style="margin-bottom:8px;">
							<h:outputText value="Import new values from uploaded file: " />
							<p:selectBooleanCheckbox id="importNewValues" value="#{brewingEditor.importNewValues}">
								<p:ajax />
							</p:selectBooleanCheckbox>
						</h:panelGrid>
						<p:fileUpload id="brewingFileUpload" allowTypes="/\.btp$/" sizeLimit="2097152"
							fileUploadListener="#{brewingEditor.uploadListener}" update="@form" process="importNewValues" />
					</ui:fragment>
						
					<p:growl id="globalGrowl" sticky="false" globalOnly="true" life="2500" autoUpdate="true" />
					
					<p:confirmDialog id="confirmDeleteDialogElement" widgetVar="confirmDeleteDialog" severity="alert"
						header="Delete Brewing"
						message="Deleting a brewing will also delete any BeerTools file stored for the brewing. Continue?">
						<p:commandButton id="deleteConfirmButton" value="Delete Brewing" action="#{brewingEditor.deleteBrewing}" ajax="false" />
						<p:commandButton id="deleteCancelButton" value="Cancel" onclick="confirmDeleteDialog.hide()" type="button" />
					</p:confirmDialog>
				</h:form>
			</p:panel>
		</ui:define>
	</ui:composition>
</body>
</html>