site/src/main/java/com/cervisium/webapp/bean/AlbumEditorBean.java
package com.cervisium.webapp.bean;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;

import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.FilenameUtils;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.PhotoFileException;
import com.cervisium.webapp.PhotoFileLocation;
import com.cervisium.webapp.Resources;
import com.cervisium.webapp.entity.Album;
import com.cervisium.webapp.entity.Photo;
import com.cervisium.webapp.services.ImageService;
import com.cervisium.webapp.services.PhotoDeleteService;

@ViewScoped
@Named("albumEditor")
public class AlbumEditorBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject @Cervisium private transient Logger log;
	@Inject private SessionState session;
	@Inject @PhotoFileLocation File photoFileLocation;
	
	@Inject private transient ImageService imageService;
	@Inject private transient PhotoDeleteService deleteService;
	
	private Integer editAlbumId;
	private Album editedAlbum;
	private String selectedPhotoIdStr;
	private Photo selectedPhoto;
	private Integer resizeMaxDim;
	
	public Integer getEditAlbumId() { return editAlbumId; }
	public void setEditAlbumId(Integer editAlbumId) { this.editAlbumId = editAlbumId; }
	public Album getEditedAlbum() { return editedAlbum; }
	public void setEditedAlbum(Album editedAlbum) { this.editedAlbum = editedAlbum; }
	public String getSelectedPhotoIdStr() { return selectedPhotoIdStr; }
	public void setSelectedPhotoIdStr(String selectedPhotoIdStr) { this.selectedPhotoIdStr = selectedPhotoIdStr; }
	public Photo getSelectedPhoto() { return selectedPhoto; }
	public void setSelectedPhoto(Photo selectedPhoto) { this.selectedPhoto = selectedPhoto; }
	public Integer getResizeMaxDim() { return resizeMaxDim; }
	public void setResizeMaxDim(Integer resizeMaxDim) { this.resizeMaxDim = resizeMaxDim; }
	
	public String getPhotoURLPrefix() {
		return Resources.getPhotoURLPrefix();
	}
	
	public void loadAlbum() {
		if (editAlbumId < 0) {
			editedAlbum = new Album();
			editedAlbum.setBrewery(session.getActiveBrewery());
		} else {
			editedAlbum = em.find(Album.class, editAlbumId);
		}
		
		selectedPhotoIdStr = null;
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void saveAlbum() throws PhotoFileException {
		if (getWritable() == false) { return; }
		
		boolean newAlbum = false;
		
		if (editedAlbum.getId() == null) {
			newAlbum = true;
			
			editedAlbum.generateFolderName();
			em.persist(editedAlbum);
			em.flush();
			editedAlbum.generateFolderName();
			em.flush();
			
			File newAlbumFolder = new File(photoFileLocation, editedAlbum.getFolder());
			if (newAlbumFolder.isDirectory() == false) { 
				newAlbumFolder.mkdir();
			}
			
			if (newAlbumFolder.isDirectory() == false) {
				String err = "Failed to create album directory: " + newAlbumFolder.getAbsolutePath();
				log.error(err);
				throw new PhotoFileException(err);
			}
			
			em.detach(editedAlbum);
		} else {
			em.merge(editedAlbum);
		}
		
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo album details saved.", null));
		
		if (newAlbum) { Navigation.navigate("/photo/album?faces-redirect=true&id=" + Integer.toString(editedAlbum.getId())); }
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void fileUploadListener(FileUploadEvent event) throws PhotoFileException {
		if (editedAlbum.getId() == null || getWritable() == false) { return; }
		
		// Prepare a record for the new photo
		Photo photo = new Photo();
		photo.setAlbum(editedAlbum);
		photo.setPhotoTime(new Date());
		
		String newFileName = FilenameUtils.simplifyFilename(event.getFile().getFileName());
		photo.setFileName(newFileName);
		
		File albumFolder = new File(photoFileLocation, editedAlbum.getFolder());
		File photoFile = new File(albumFolder, newFileName);
		FileOutputStream photoOut = null;
		
		try {
			photoOut = new FileOutputStream(photoFile);
			IOUtils.copy(event.getFile().getInputstream(), photoOut);
		} catch (IOException ioe) {
			String err = "Failed to save photo file: " + photoFile.getAbsolutePath();
			log.error(err, ioe);
			throw new PhotoFileException(err, ioe);
		} finally {
			if (photoOut != null) { try { photoOut.close(); } catch (IOException ioe2) {} }
		}
		
		// File saved okay, persist the photo
		em.persist(photo);
		em.flush();
		
		imageService.generateThumb(photo);
		
		loadAlbum();
	}
	
	public void rethumbAlbum() {
		if (getWritable() == false) { return; }
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Initiated background regeneration of thumbnails.", null));
		imageService.rethumbAlbum(editedAlbum);
	}
	
	public void photoClickListener() {
		Integer selectedPhotoId = Integer.parseInt(selectedPhotoIdStr);
		selectedPhoto = em.find(Photo.class, selectedPhotoId);
	}
	
	public void saveSelectedPhoto() {
		if (getWritable() == false) { return; }
		em.merge(selectedPhoto);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo saved.", null));
	}
	
	public void resizeSelectedPhoto() {
		if (getWritable() == false) { return; }
		if (resizeMaxDim == null || resizeMaxDim < 100) {
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Resize max dimension too small, must be greater than 100", null));
			return;
		}
		
		imageService.resizePhoto(selectedPhoto, resizeMaxDim);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo resized.", null));
	}
	
	public void deleteSelectedPhoto() {
		if (getWritable() == false) { return; }
		deleteService.deletePhoto(selectedPhoto);
		loadAlbum();
	}
	
	public String deleteAlbum() {
		if (getWritable() == false) { return ""; }
		deleteService.deleteAlbum(editedAlbum);
		return "/photo/manage?faces-redirect=true";
	}
	
	public boolean getWritable() {
		if (session.getLoggedIn() == false || session.getLoggedInUser().getPrivManagePhotos() == false) { return false; }
		if (editedAlbum.getBrewery().getId() != session.getLoggedInUser().getBrewery().getId()) { return false; }
		
		return true;
	}
}

site/src/main/java/com/cervisium/webapp/bean/AlbumManagerBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.entity.Album;

@ViewScoped
@Named("albumManager")
public class AlbumManagerBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private List<Album> albums;
	
	public List<Album> getAlbums() { return albums; }
	
	@PostConstruct
	public void init() {
		albums = em.createQuery("SELECT a FROM Album a WHERE a.brewery.id = :breweryId ORDER BY a.addedTime DESC", Album.class)
			.setParameter("breweryId", session.getActiveBrewery().getId()).getResultList();
	}
}

site/src/main/java/com/cervisium/webapp/bean/AuthBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.validation.constraints.NotNull;

import org.apache.log4j.Logger;
import org.hibernate.validator.constraints.Email;
import org.mindrot.jbcrypt.BCrypt;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.PasswordChange;
import com.cervisium.webapp.entity.BreweryUser;

@ViewScoped
@Named("auth")
public class AuthBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient Logger log;
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private String email;
	private String password;
	private PasswordChange passwordChange;
	private UIComponent authForm;
	private UIComponent passwordChangeForm;
	private UIComponent newPasswordConfirm;
	
	@PostConstruct
	public void init() {
		passwordChange = new PasswordChange();
	}
	
	@Email(message = "Must be a valid email address")
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	@NotNull(message = "Please enter your password")
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public UIComponent getAuthForm() {
		return authForm;
	}
	
	public void setAuthForm(UIComponent authForm) {
		this.authForm = authForm;
	}
	
	public PasswordChange getPasswordChange() {
		return passwordChange;
	}
	
	public void setPasswordChange(PasswordChange passwordChange) {
		this.passwordChange = passwordChange;
	}
	
	public UIComponent getNewPasswordConfirm() {
		return newPasswordConfirm;
	}
	
	public void setNewPasswordConfirm(UIComponent newPasswordConfirm) {
		this.newPasswordConfirm = newPasswordConfirm;
	}
	
	public UIComponent getPasswordChangeForm() {
		return passwordChangeForm;
	}
	
	public void setPasswordChangeForm(UIComponent passwordChangeForm) {
		this.passwordChangeForm = passwordChangeForm;
	}
	
	public void login() {
		try {
			BreweryUser user = em.createQuery("SELECT u FROM BreweryUser u WHERE u.email = :email", BreweryUser.class)
				.setParameter("email", getEmail()).getSingleResult();
			if (user == null) { throw new NoResultException(); }
			
			if (BCrypt.checkpw(password, user.getPassHash())) {
				loginSuccess(user);
			} else {
				addLoginFailMessage();
			}
		} catch (NoResultException nre) {
			try { Thread.sleep(500 + (long)Math.floor(Math.random() * 500)); } catch (InterruptedException ie) { }
			addLoginFailMessage();
		}
		
		passwordChange = new PasswordChange();
	}
	
	public void logout() {
		email = null;
		password = null;
		session.setLoggedInUser(null);
		passwordChange = new PasswordChange();
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void changePassword() {
		BreweryUser user = em.find(BreweryUser.class, session.getLoggedInUser().getId());
		if (user == null) {
			addPasswordChangeMessage("Error updating user password", FacesMessage.SEVERITY_ERROR);
			logout();
		} else {
			if (passwordChange.getNewPassword().equals(passwordChange.getNewPasswordConfirm()) == false) {
				FacesContext.getCurrentInstance().addMessage(newPasswordConfirm.getClientId(),
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Must match New Password", null));
			} else {
				if (BCrypt.checkpw(passwordChange.getOldPassword(), user.getPassHash())) {
					String newHash = BCrypt.hashpw(passwordChange.getNewPassword(), BCrypt.gensalt(12));
					user.setPassHash(newHash);
					em.flush();
					
					addPasswordChangeMessage("Password Changed.", FacesMessage.SEVERITY_INFO);
					
					passwordChange = new PasswordChange();
				} else {
					addPasswordChangeMessage("Old password incorrect, please try again.", FacesMessage.SEVERITY_ERROR);
				}
			}
		}
	}
	
	public void cancelChangePassword() {
		passwordChange = new PasswordChange();
	}
	
	protected void addLoginFailMessage() {
		addLoginFailMessage("Login failed, Please try again.");
	}
	
	protected void addLoginFailMessage(String message) {
		FacesContext.getCurrentInstance().addMessage(authForm.getClientId(),
				new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
		log.error("Login failure for " + (email != null ? email : "NULL"));
	}
	
	protected void addPasswordChangeMessage(String message, Severity severity) {
		FacesContext.getCurrentInstance().addMessage(passwordChangeForm.getClientId(),
				new FacesMessage(severity, message, null));
	}
	
	protected void loginSuccess(BreweryUser user) {
		log.info("Login: " + email);
		
		em.detach(user);
		user.setPassHash(null);
		password = null;
		
		session.setLoggedInUser(user);
	}
}

site/src/main/java/com/cervisium/webapp/bean/InventoryBean.java
package com.cervisium.webapp.bean;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.joda.time.DateTime;
import org.joda.time.Days;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.InventoryItem;
import com.cervisium.webapp.entity.Brewing;

@Named("inventory")
@RequestScoped
public class InventoryBean {

	@Inject @Cervisium private EntityManager em;

	private ArrayList<InventoryItem> inventoryItems;
	
	public ArrayList<InventoryItem> getInventoryItems() {
		return inventoryItems;
	}
	
	public void setInventoryItems(ArrayList<InventoryItem> inventoryItems) {
		this.inventoryItems = inventoryItems;
	}
	
	@PostConstruct
	public void init() {
		inventoryItems = new ArrayList<InventoryItem>();
		
		List<Brewing> brewings = em.createQuery("SELECT b FROM Brewing b where dateFinish = NULL", Brewing.class)
			.getResultList();
		
		for (Brewing brewing : brewings) {
			InventoryItem item = new InventoryItem();
			item.setName(brewing.getFormulation().getRecipe().getName() + " - " + brewing.getFormulation().getName());
			item.setBrewingId(brewing.getId());
			item.setDateBrew(brewing.getDateBrew());
			item.setDateSecondary(brewing.getDateSecondary());
			item.setDateKeg(brewing.getDateKeg());
			item.setDateBottle(brewing.getDateBottle());
			item.setStage(brewing.getBrewStage());
			
			Days age = Days.daysBetween(new DateTime(brewing.getDateBrew()), new DateTime());
			item.setAgeDays(age.getDays());
			
			inventoryItems.add(item);
		}
		
		Collections.sort(inventoryItems);
	}
}

site/src/main/java/com/cervisium/webapp/bean/NewsBean.java
package com.cervisium.webapp.bean;

import java.util.List;

import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.entity.NewsItem;

@RequestScoped
@Named("news")
public class NewsBean {

	@Inject @Cervisium private EntityManager em;
	@Inject private SessionState session;
	
	private List<NewsItem> newsItems;
	private Integer offset;
	private Integer nextOffset;
	private Boolean renderMoreLink = Boolean.FALSE;
	
	public List<NewsItem> getNewsItems() { return newsItems; }
	public void setNewsItems(List<NewsItem> newsItems) { this.newsItems = newsItems; }
	public Integer getOffset() { return offset; }
	public void setOffset(Integer offset) { this.offset = offset; }
	public Integer getNextOffset() { return nextOffset; }
	public void setNextOffset(Integer nextOffset) { this.nextOffset = nextOffset; }
	public Boolean getRenderMoreLink() { return renderMoreLink; }
	public void setRenderMoreLink(Boolean renderMoreLink) { this.renderMoreLink = renderMoreLink; }
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void loadNewsItems() {
		if (offset == null) { offset = 0; }
		
		newsItems = em.createQuery("SELECT ni FROM NewsItem ni WHERE ni.breweryId = :breweryId " +
			"ORDER BY ni.postDate DESC", NewsItem.class)
			.setParameter("breweryId", session.getActiveBrewery().getId())
			.setFirstResult(offset).setMaxResults(10).getResultList();
		
		nextOffset = offset + 10;
		
		if (newsItems.size() == 10) { renderMoreLink = Boolean.TRUE; }
	}
}

site/src/main/java/com/cervisium/webapp/entity/BrewStage.java
package com.cervisium.webapp.entity;

public enum BrewStage {

	PRIMARY("Primary", 50),
	SECONDARY("Secondary", 40),
	KEG("Keg", 30),
	BOTTLES("Bottles", 20),
	FINISHED("Finished", 10);
	
	private String stageName;
	private int orderPoints;
	
	private BrewStage(String stageName, int orderPoints) {
		this.stageName = stageName;
		this.orderPoints = orderPoints;
	}
	
	public String getStageName() {
		return stageName;
	}
	
	public int getOrderPoints() {
		return orderPoints;
	}
}

site/src/main/webapp/photo/album.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">

<body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="body">
			<f:metadata>
				<f:viewParam name="id" value="#{albumEditor.editAlbumId}" />
				<s:viewAction action="#{albumEditor.loadAlbum}" />
			</f:metadata>
			
			<h:outputStylesheet library="css" name="photoalbum-201208191447.css" />
		
			<h2>Photo Album</h2>
			<h:form id="albumForm" prependId="false">
				<p:panel id="albumPanel" style="margin-bottom:16px;">
					<h:panelGrid columns="3" cellspacing="3" style="margin-bottom:16px;">
						<p:outputLabel for="albumName" value="Name: " />
						<p:inputText id="albumName" value="#{albumEditor.editedAlbum.name}" style="width:300px;" />
						<p:message for="albumName" />
						<p:outputLabel for="addedTime" value="Added: " />
						<p:calendar id="addedTime" value="#{albumEditor.editedAlbum.addedTime}" readonlyInput="true"
							pattern="yyyy-MM-dd h:mm a" />
						<p:message for="addedTime" />
					</h:panelGrid>
					
					<p:commandButton id="saveAlbumButton" value="Save Album" action="#{albumEditor.saveAlbum}" update="@form"
						style="margin-right:8px;" />
					<p:commandButton id="deleteAlbumButton" value="Delete Album" type="button" onclick="confirmDeleteDialog.show()" />
				</p:panel>
				
				<p:confirmDialog id="confirmDeleteDialogElement" widgetVar="confirmDeleteDialog" severity="alert"
					header="Delete Album"
					message="Deleting an album will delete all photos contained within. Continue?">
					<p:commandButton id="deleteConfirmButton" value="Delete Album" action="#{albumEditor.deleteAlbum}" ajax="false" />
					<p:commandButton id="deleteCancelButton" value="Cancel" onclick="confirmDeleteDialog.hide()" type="button" />
				</p:confirmDialog>
			</h:form>
			
			<h:form id="photoForm" prependId="false">
				<p:panel id="photoPanel" header="Photos" rendered="#{albumEditor.editedAlbum.id != null}" style="margin-bottom:16px;">
					<p:outputPanel id="photoPanelOutput" layout="block" style="margin-bottom:16px;">
						<ui:repeat var="photo" value="#{albumEditor.editedAlbum.photos}">
							<p:commandLink action="#{albumEditor.photoClickListener}" styleClass="photoItem"
								update=":photoForm:viewImageDialogElement" oncomplete="viewImageDialog.show()">
								<f:setPropertyActionListener target="#{albumEditor.selectedPhotoIdStr}" value="#{photo.id}" />
								<ui:fragment rendered="#{photo.thumbnail != null}">
									<img src="#{albumEditor.photoURLPrefix}#{albumEditor.editedAlbum.folder}/#{photo.thumbnail}" alt="thumbnail" />
								</ui:fragment>
								<h:graphicImage library="img" name="nothumb.png" rendered="#{photo.thumbnail == null}" />
							</p:commandLink>
						</ui:repeat>
						<div style="clear:both;"></div>
					</p:outputPanel>
					
					<p:commandButton id="rethumbButton" value="Regenerate Thumbnails" action="#{albumEditor.rethumbAlbum}" />
				</p:panel>
				
				<p:dialog id="viewImageDialogElement" widgetVar="viewImageDialog" header="Image Details" position="center">
					<ui:fragment rendered="#{albumEditor.selectedPhoto != null}">
						<div class="dialogImageHolder">
							<img src="#{albumEditor.photoURLPrefix}#{albumEditor.editedAlbum.folder}/#{albumEditor.selectedPhoto.fileName}"
								alt="#{albumEditor.selectedPhoto.fileName}" class="dialogImage" />
						</div>
						<h:panelGrid columns="3" style="margin-bottom:16px;">
							<h:outputText value="Image URL:" />
							<h:outputText value="#{albumEditor.photoURLPrefix}#{albumEditor.editedAlbum.folder}/#{albumEditor.selectedPhoto.fileName}" />
							<h:outputText value=" " />
							
							<p:outputLabel for="editPhotoTag" value="Tag:" />
							<p:inputText id="editPhotoTag" value="#{albumEditor.selectedPhoto.tag}" style="width:260px;" />
							<p:message for="editPhotoTag" />
							
							<p:outputLabel for="editPhotoResizeMaxDim" value="Resize To Px Max:" />
							<p:selectOneMenu id="editPhotoResizeMaxDim" value="#{albumEditor.resizeMaxDim}" editable="true">
								<f:selectItem itemLabel="860" itemValue="860"/>
								<f:selectItem itemLabel="430" itemValue="430"/>
							</p:selectOneMenu>
							<p:message for="editPhotoResizeMaxDim" />
						</h:panelGrid>
					</ui:fragment>
					<p:commandButton id="editPhotoSave" value="Save Changes" action="#{albumEditor.saveSelectedPhoto}" style="margin-right:8px;" />
					<p:commandButton id="editPhotoResize" value="Resize Image" action="#{albumEditor.resizeSelectedPhoto}"
						update=":photoForm:viewImageDialogElement" style="margin-right:8px;" />
					<p:commandButton id="editPhotoDelete" value="Delete Photo" action="#{albumEditor.deleteSelectedPhoto}"
						update=":photoForm" oncomplete="viewImageDialog.hide()" style="margin-right:8px;" />
					<p:commandButton id="closeImageDialogButton" value="Close" type="button" onclick="viewImageDialog.hide()" />
				</p:dialog>
			</h:form>
			
			<h:form id="uploadForm" prependId="false">
				<p:panel id="uploadPanel" header="Upload Photos" rendered="#{albumEditor.editedAlbum.id != null}">
					<p:fileUpload id="photoUploader" fileUploadListener="#{albumEditor.fileUploadListener}" sizeLimit="6291456"
						allowTypes="/\.(jpg|png|JPG|PNG)$/" multiple="true" mode="advanced" update=":photoForm:photoPanelOutput" />
				</p:panel>
			</h:form>
			
			<p:growl id="globalGrowl" globalOnly="true" life="4000" sticky="false" autoUpdate="true" />
		</ui:define>
	</ui:composition>
</body>
</html>

site/src/main/webapp/photo/manage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">

<body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="menuItems">
			<ui:fragment rendered="#{sessionState.loggedInUser.privManagePhotos}">
				| <h:link id="createAlbumLink" value="Create Album" outcome="/photo/album">
					<f:param name="id" value="-1" />
				</h:link>
			</ui:fragment>
		</ui:define>
		<ui:define name="body">
			<h2>Manage Photos</h2>
			<p>Select an album from the list to view its contents.</p>
			<h:form id="albumListForm" prependId="false">
				<p:dataTable id="albumListTable" value="#{albumManager.albums}" var="album" styleClass="linkList">
					<f:facet name="header">Photo Albums</f:facet>
					<p:column>
						<f:facet name="header">Name</f:facet>
						<h:link outcome="/photo/album?faces-redirect=true">
							<f:param name="id" value="#{album.id}" />
							<h:outputText value="#{album.name}" />
						</h:link>
					</p:column>
					<p:column>
						<f:facet name="header">Added</f:facet>
						<h:link outcome="/photo/album?faces-redirect=true">
							<f:param name="id" value="#{album.id}" />
							<h:outputText value="#{album.addedTime}">
								<f:convertDateTime pattern="yyyy-MM-dd h:mm a" />
							</h:outputText>
						</h:link>
					</p:column>
				</p:dataTable>
			</h:form>
		</ui:define>
	</ui:composition>
</body>
</html>