site/src/main/java/com/cervisium/webapp/bean/AlbumEditorBean.java
package com.cervisium.webapp.bean;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;

import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.FilenameUtils;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.PhotoFileException;
import com.cervisium.webapp.PhotoFileLocation;
import com.cervisium.webapp.Resources;
import com.cervisium.webapp.entity.Album;
import com.cervisium.webapp.entity.Photo;
import com.cervisium.webapp.services.ImageService;
import com.cervisium.webapp.services.PhotoDeleteService;

@ViewScoped
@Named("albumEditor")
public class AlbumEditorBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject @Cervisium private transient Logger log;
	@Inject private SessionState session;
	@Inject @PhotoFileLocation File photoFileLocation;
	
	@Inject private transient ImageService imageService;
	@Inject private transient PhotoDeleteService deleteService;
	
	private Integer editAlbumId;
	private Album editedAlbum;
	private String selectedPhotoIdStr;
	private Photo selectedPhoto;
	private Integer resizeMaxDim;
	
	public Integer getEditAlbumId() { return editAlbumId; }
	public void setEditAlbumId(Integer editAlbumId) { this.editAlbumId = editAlbumId; }
	public Album getEditedAlbum() { return editedAlbum; }
	public void setEditedAlbum(Album editedAlbum) { this.editedAlbum = editedAlbum; }
	public String getSelectedPhotoIdStr() { return selectedPhotoIdStr; }
	public void setSelectedPhotoIdStr(String selectedPhotoIdStr) { this.selectedPhotoIdStr = selectedPhotoIdStr; }
	public Photo getSelectedPhoto() { return selectedPhoto; }
	public void setSelectedPhoto(Photo selectedPhoto) { this.selectedPhoto = selectedPhoto; }
	public Integer getResizeMaxDim() { return resizeMaxDim; }
	public void setResizeMaxDim(Integer resizeMaxDim) { this.resizeMaxDim = resizeMaxDim; }
	
	public String getPhotoURLPrefix() {
		return Resources.getPhotoURLPrefix();
	}
	
	public void loadAlbum() {
		if (editAlbumId < 0) {
			editedAlbum = new Album();
			editedAlbum.setBrewery(session.getActiveBrewery());
		} else {
			editedAlbum = em.find(Album.class, editAlbumId);
		}
		
		selectedPhotoIdStr = null;
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void saveAlbum() throws PhotoFileException {
		if (getWritable() == false) { return; }
		
		boolean newAlbum = false;
		
		if (editedAlbum.getId() == null) {
			newAlbum = true;
			
			editedAlbum.generateFolderName();
			em.persist(editedAlbum);
			em.flush();
			editedAlbum.generateFolderName();
			em.flush();
			
			File newAlbumFolder = new File(photoFileLocation, editedAlbum.getFolder());
			if (newAlbumFolder.isDirectory() == false) { 
				newAlbumFolder.mkdir();
			}
			
			if (newAlbumFolder.isDirectory() == false) {
				String err = "Failed to create album directory: " + newAlbumFolder.getAbsolutePath();
				log.error(err);
				throw new PhotoFileException(err);
			}
			
			em.detach(editedAlbum);
		} else {
			em.merge(editedAlbum);
		}
		
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo album details saved.", null));
		
		if (newAlbum) { Navigation.navigate("/photo/album?faces-redirect=true&id=" + Integer.toString(editedAlbum.getId())); }
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void fileUploadListener(FileUploadEvent event) throws PhotoFileException {
		if (editedAlbum.getId() == null || getWritable() == false) { return; }
		
		// Prepare a record for the new photo
		Photo photo = new Photo();
		photo.setAlbum(editedAlbum);
		photo.setPhotoTime(new Date());
		
		String newFileName = FilenameUtils.simplifyFilename(event.getFile().getFileName());
		photo.setFileName(newFileName);
		
		File albumFolder = new File(photoFileLocation, editedAlbum.getFolder());
		File photoFile = new File(albumFolder, newFileName);
		FileOutputStream photoOut = null;
		
		try {
			photoOut = new FileOutputStream(photoFile);
			IOUtils.copy(event.getFile().getInputstream(), photoOut);
		} catch (IOException ioe) {
			String err = "Failed to save photo file: " + photoFile.getAbsolutePath();
			log.error(err, ioe);
			throw new PhotoFileException(err, ioe);
		} finally {
			if (photoOut != null) { try { photoOut.close(); } catch (IOException ioe2) {} }
		}
		
		// File saved okay, persist the photo
		em.persist(photo);
		em.flush();
		
		imageService.generateThumb(photo);
		
		loadAlbum();
	}
	
	public void rethumbAlbum() {
		if (getWritable() == false) { return; }
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Initiated background regeneration of thumbnails.", null));
		imageService.rethumbAlbum(editedAlbum);
	}
	
	public void photoClickListener() {
		Integer selectedPhotoId = Integer.parseInt(selectedPhotoIdStr);
		selectedPhoto = em.find(Photo.class, selectedPhotoId);
	}
	
	public void saveSelectedPhoto() {
		if (getWritable() == false) { return; }
		em.merge(selectedPhoto);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo saved.", null));
	}
	
	public void resizeSelectedPhoto() {
		if (getWritable() == false) { return; }
		if (resizeMaxDim == null || resizeMaxDim < 100) {
			FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_ERROR, "Resize max dimension too small, must be greater than 100", null));
			return;
		}
		
		imageService.resizePhoto(selectedPhoto, resizeMaxDim);
		FacesContext.getCurrentInstance().addMessage(null,
			new FacesMessage(FacesMessage.SEVERITY_INFO, "Photo resized.", null));
	}
	
	public void deleteSelectedPhoto() {
		if (getWritable() == false) { return; }
		deleteService.deletePhoto(selectedPhoto);
		loadAlbum();
	}
	
	public String deleteAlbum() {
		if (getWritable() == false) { return ""; }
		deleteService.deleteAlbum(editedAlbum);
		return "/photo/manage?faces-redirect=true";
	}
	
	public boolean getWritable() {
		if (session.getLoggedIn() == false || session.getLoggedInUser().getPrivManagePhotos() == false) { return false; }
		if (editedAlbum.getBrewery().getId() != session.getLoggedInUser().getBrewery().getId()) { return false; }
		
		return true;
	}
}

site/src/main/java/com/cervisium/webapp/bean/AlbumManagerBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.entity.Album;

@ViewScoped
@Named("albumManager")
public class AlbumManagerBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private List<Album> albums;
	
	public List<Album> getAlbums() { return albums; }
	
	@PostConstruct
	public void init() {
		albums = em.createQuery("SELECT a FROM Album a WHERE a.brewery.id = :breweryId ORDER BY a.addedTime DESC", Album.class)
			.setParameter("breweryId", session.getActiveBrewery().getId()).getResultList();
	}
}

site/src/main/java/com/cervisium/webapp/bean/InventoryBean.java
package com.cervisium.webapp.bean;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.joda.time.DateTime;
import org.joda.time.Days;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.InventoryItem;
import com.cervisium.webapp.entity.Brewing;

@Named("inventory")
@RequestScoped
public class InventoryBean {

	@Inject @Cervisium private EntityManager em;

	private ArrayList<InventoryItem> inventoryItems;
	
	public ArrayList<InventoryItem> getInventoryItems() {
		return inventoryItems;
	}
	
	public void setInventoryItems(ArrayList<InventoryItem> inventoryItems) {
		this.inventoryItems = inventoryItems;
	}
	
	@PostConstruct
	public void init() {
		inventoryItems = new ArrayList<InventoryItem>();
		
		List<Brewing> brewings = em.createQuery("SELECT b FROM Brewing b where dateFinish = NULL", Brewing.class)
			.getResultList();
		
		for (Brewing brewing : brewings) {
			InventoryItem item = new InventoryItem();
			item.setName(brewing.getFormulation().getRecipe().getName() + " - " + brewing.getFormulation().getName());
			item.setBrewingId(brewing.getId());
			item.setDateBrew(brewing.getDateBrew());
			item.setDateSecondary(brewing.getDateSecondary());
			item.setDateKeg(brewing.getDateKeg());
			item.setDateBottle(brewing.getDateBottle());
			item.setStage(brewing.getBrewStage());
			
			Days age = Days.daysBetween(new DateTime(brewing.getDateBrew()), new DateTime());
			item.setAgeDays(age.getDays());
			
			inventoryItems.add(item);
		}
		
		Collections.sort(inventoryItems);
	}
}

site/src/main/java/com/cervisium/webapp/bean/NewsManagerBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.Navigation;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.entity.NewsItem;

@ViewScoped
@Named("newsManager")
public class NewsManagerBean implements Serializable {
	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	private List<NewsItem> newsItems;
	
	@PostConstruct
	public void init() {
		loadNewsItems();
	}
	
	public List<NewsItem> getNewsItems() { return newsItems; }
	
	protected void loadNewsItems() {
		newsItems = em.createQuery(
			"SELECT ni FROM NewsItem ni WHERE ni.breweryId = :breweryId ORDER BY ni.postDate DESC", NewsItem.class)
			.setParameter("breweryId", session.getActiveBrewery().getId())
			.getResultList();
	}
}

site/src/main/java/com/cervisium/webapp/bean/RecipeEditorBean.java
package com.cervisium.webapp.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.log4j.Logger;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.bean.model.IntegerKeyedModel;
import com.cervisium.webapp.entity.Brewer;
import com.cervisium.webapp.entity.Formulation;
import com.cervisium.webapp.entity.Recipe;
import com.cervisium.webapp.services.RecipeDeleteService;

@Named("recipeEditor")
@ViewScoped
public class RecipeEditorBean implements Serializable {

	public static final long serialVersionUID = 1l;
	
	@Inject @Cervisium private transient Logger log;
	@Inject @Cervisium private transient EntityManager em;
	@Inject private SessionState session;
	
	@Inject RecipeDeleteService deleteService;
	
	private Integer editRecipeId;
	private Recipe editedRecipe;
	
	private List<Brewer> brewers;
	private Integer selectedAddAuthor;
	private Integer selectedRemoveAuthor;
	private SelectItem noBrewerSelectionItem = new SelectItem(new Integer(-1), "Select Brewer...");
	
	@PostConstruct
	public void init() {
		brewers = em.createQuery("SELECT b FROM Brewer b WHERE b.breweryId = :breweryId", Brewer.class)
			.setParameter("breweryId", session.getActiveBrewery().getId())
			.getResultList();
		selectedAddAuthor = -1;
	}
	
	public Recipe getEditedRecipe() { return editedRecipe; }
	public void setEditedRecipe(Recipe editedRecipe) { this.editedRecipe = editedRecipe; }
	public Integer getEditRecipeId() { return editRecipeId; }
	public void setEditRecipeId(Integer editRecipeId) { this.editRecipeId = editRecipeId; }
	public List<Brewer> getBrewers() { return brewers; }
	public Integer getSelectedAddAuthor() { return selectedAddAuthor; }
	public void setSelectedAddAuthor(Integer selectedAddAuthor) { this.selectedAddAuthor = selectedAddAuthor; }
	public Integer getSelectedRemoveAuthor() { return selectedRemoveAuthor; }
	public void setSelectedRemoveAuthor(Integer selectedRemoveAuthor) { this.selectedRemoveAuthor = selectedRemoveAuthor; }
	public SelectItem getNoBrewerSelectionItem() { return noBrewerSelectionItem; }
	
	public boolean getWritable() {
		if (session.getLoggedIn()) {
			if (session.getLoggedInUser().getBrewery().getId() == editedRecipe.getBreweryId()) {
				return true;
			}
		}
		
		return false;
	}
	
	public List<SelectItem> getBrewerItems() {
		ArrayList<SelectItem> items = new ArrayList<SelectItem>();
		for (Brewer b : getBrewers()) {
			if (editedRecipe.getAuthors().contains(b) == false) {
				items.add(new SelectItem(b.getId(), b.getName()));
			}
		}
		return items;
	}
	
	public void addSelectedAuthor() {
		if (selectedAddAuthor != null && selectedAddAuthor >= 0) {
			Brewer author = em.find(Brewer.class, selectedAddAuthor);
			if (editedRecipe.getAuthors().contains(author) == false) {
				editedRecipe.getAuthors().add(author);
			}
		}
		
		selectedAddAuthor = -1;
	}
	
	public void loadRecipe() {
		if (editRecipeId == -1) {
			editedRecipe = new Recipe();
			editedRecipe.setBreweryId(session.getActiveBrewery().getId());
		} else {
			editedRecipe = em.find(Recipe.class, editRecipeId);
		}
	}
	
	@TransactionAttribute(TransactionAttributeType.REQUIRED)
	public void saveRecipe() {
		if (getWritable() == false) { return; }
		
		if (editedRecipe.getId() == null) {
			em.persist(editedRecipe);
		}
		
		em.merge(editedRecipe);
		
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Recipe Saved", null));
	}
	
	public String deleteRecipe() {
		if (getWritable() == false) { return ""; }
		
		deleteService.deleteRecipe(editedRecipe);
		return "/recipes/index?faces-redirect=true";
	}
	
	public void removeAuthor() {
		if (selectedRemoveAuthor != null) {
			Brewer brewerToRemove = null;
			for (Brewer b : editedRecipe.getAuthors()) {
				if (b.getId() == selectedRemoveAuthor) { brewerToRemove = b; }
			}
			
			if (brewerToRemove != null) { editedRecipe.getAuthors().remove(brewerToRemove); }
		}
	}
}

site/src/main/java/com/cervisium/webapp/bean/SessionState.java
package com.cervisium.webapp.bean;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.log4j.Logger;

import com.cervisium.webapp.Cervisium;
import com.cervisium.webapp.entity.Brewery;
import com.cervisium.webapp.entity.BreweryUser;

@Named("sessionState")
@SessionScoped
public class SessionState implements Serializable {
	public static final long serialVersionUID = 1l;

	@Inject @Cervisium private transient Logger log;
	@Inject @Cervisium private transient EntityManager em;
	
	private BreweryUser loggedInUser;
	private Brewery activeBrewery;
	
	@PostConstruct
	public void init() {
		activeBrewery = em.createQuery("SELECT b FROM Brewery b WHERE b.name = :name", Brewery.class)
			.setParameter("name", "Cervisium")
			.getSingleResult();
		if (activeBrewery != null) {
			log.info("Loaded default brewery: " + activeBrewery.getName());
		} else {
			log.error("Failed to find default brewery Cervisium");
		}
		
		loggedInUser = null;
	}
	
	public Brewery getActiveBrewery() {
		return activeBrewery;
	}
	
	public void setActiveBrewery(Brewery activeBrewery) {
		this.activeBrewery = activeBrewery;
	}

	public boolean getLoggedIn() {
		return (loggedInUser != null);
	}
	
	public BreweryUser getLoggedInUser() {
		return loggedInUser;
	}
	
	public void setLoggedInUser(BreweryUser loggedInUser) {
		this.loggedInUser = loggedInUser;
	}
	
	public boolean getUserActiveBreweryMember() {
		if (getLoggedIn()) {
			if (getLoggedInUser().getBrewery().getId() == getActiveBrewery().getId()) {
				return true;
			}
		}
		
		return false;
	}
}

site/src/main/webapp/recipes/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:s="http://jboss.org/seam/faces"
	xmlns:p="http://primefaces.org/ui">

<body>
	<ui:composition template="/templates/template.xhtml">
		<f:metadata>
			<f:viewParam name="id" value="#{recipeEditor.editRecipeId}" />
			<s:viewAction action="#{recipeEditor.loadRecipe}" />
		</f:metadata>
		<ui:define name="body">
			<style type="text/css">
				.inpSize { width: 280px; }
				.spaceRight { margin-right: 8px; }
				.spaceBottom { margin-bottom: 16px; }
			</style>
			<p:panel header="Edit Recipe" style="margin-bottom: 16px;">
				<h:form id="editRecipeForm" prependId="false">
					<h:panelGrid columns="3" cellspacing="3" style="margin-bottom:16px;">
						<h:outputText value="Recipe Name: " />
						<p:inputText id="recipeName" value="#{recipeEditor.editedRecipe.name}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}" />
						<p:message for="recipeName" />
						
						<h:outputText value="Style: " />
						<p:inputText id="recipeStyle" value="#{recipeEditor.editedRecipe.style}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}" />
						<p:message for="recipeStyle" />
						
						<h:outputText value="Target OG: " />
						<p:inputText id="recipeTargetOG" value="#{recipeEditor.editedRecipe.targetOg}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}">
							<f:convertNumber pattern="#0.000"/>
						</p:inputText>
						<p:message for="recipeTargetOG" />
						
						<h:outputText value="Target FG: " />
						<p:inputText id="recipeTargetFG" value="#{recipeEditor.editedRecipe.targetFg}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}">
							<f:convertNumber pattern="#0.000"/>
						</p:inputText>
						<p:message for="recipeTargetFG" />
						
						<h:outputText value="Target IBU: " />
						<p:inputText id="recipeTargetIBU" value="#{recipeEditor.editedRecipe.targetIBU}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}" />
						<p:message for="recipeTargetIBU" />
						
						<h:outputText value="Target SRM: " />
						<p:inputText id="recipeTargetSRM" value="#{recipeEditor.editedRecipe.targetSRM}" styleClass="inpSize"
							readonly="#{recipeEditor.writable == false}" />
						<p:message for="recipeTargetSRM" />
					</h:panelGrid>
					
					<ui:fragment rendered="#{recipeEditor.writable}">
						<p:commandButton id="saveButton" value="Save Recipe" action="#{recipeEditor.saveRecipe}" update="@form, :formulationsForm" styleClass="spaceRight"/>
						<p:commandButton id="deleteButton" value="Delete Recipe" type="button" onclick="confirmDeleteDialog.show()" />
					</ui:fragment>
					
					<p:confirmDialog id="confirmDeleteDialogElement" widgetVar="confirmDeleteDialog" severity="alert"
						header="Delete Recipe"
						message="Deleting a recipe will delete all associated formulations and brewings, including any BeerTools files stored for them. Continue?">
						<p:commandButton id="deleteConfirmButton" value="Delete Recipe" action="#{recipeEditor.deleteRecipe}" ajax="false" />
						<p:commandButton id="deleteCancelButton" value="Cancel" onclick="confirmDeleteDialog.hide()" type="button" />
					</p:confirmDialog>
				</h:form>
				<h3>Authors:</h3>
				<h:form id="authorsForm">
					<p:outputPanel id="authorList">
						<ul>
							<ui:repeat value="#{recipeEditor.editedRecipe.authors}" var="author">
								<li>
									<h:outputText value="#{author.name}" />
									<ui:fragment rendered="#{recipeEditor.writable}">
										 - <p:commandLink value="Remove" action="#{recipeEditor.removeAuthor}" update="@form">
											<f:setPropertyActionListener target="#{recipeEditor.selectedRemoveAuthor}" value="#{author.id}" />
										</p:commandLink>
									</ui:fragment>
								</li>
							</ui:repeat>
						</ul>
					</p:outputPanel>
					<ui:fragment rendered="#{recipeEditor.writable}">
						<h:panelGrid columns="3">
							<h:outputText value="Add Author" />
							<p:selectOneMenu id="selectAddAuthor" value="#{recipeEditor.selectedAddAuthor}" >
								<f:selectItem value="#{recipeEditor.noBrewerSelectionItem}" />
								<f:selectItems value="#{recipeEditor.brewerItems}" />
							</p:selectOneMenu>
							<p:commandButton id="addAuthorButton" value="Add" action="#{recipeEditor.addSelectedAuthor}" update="@form" />
						</h:panelGrid>
					</ui:fragment>
				</h:form>
			</p:panel>
			<h:form id="formulationsForm">
				<p:outputPanel id="formulationsPanel" rendered="#{recipeEditor.editedRecipe.id != null}">
					<p:panel header="Formulations">
						<p>Click a formulation in the list below to view details and brewings.</p>
						<p:dataTable id="formulationsTable" value="#{recipeEditor.editedRecipe.formulations}" var="formulation"
							styleClass="linkList" style="margin-bottom:16px;">
							<p:column>
						        <f:facet name="header">Name</f:facet>
						        <h:link outcome="/recipes/formulation?faces-redirect=true">
						        	<f:param name="id" value="#{formulation.id}" />
									<h:outputText value="#{formulation.name}" />
								</h:link>
						    </p:column>
						    <p:column>
						    	<f:facet name="header">Target Size</f:facet>
						    	<h:link outcome="/recipes/formulation?faces-redirect=true">
						        	<f:param name="id" value="#{formulation.id}" />
						    		<h:outputText value="#{formulation.targetSizeGallons}" />
						    	</h:link>
						    </p:column>
						    <p:column>
						    	<f:facet name="header">Description</f:facet>
						    	<h:link outcome="/recipes/formulation?faces-redirect=true">
						        	<f:param name="id" value="#{formulation.id}" />
						    		<h:outputText value="#{formulation.description}" />
						    	</h:link>
						    </p:column>
						</p:dataTable>
						
						<ui:fragment rendered="#{recipeEditor.writable}">
							<p:button id="newForumlationButton" value="Add Formulation" outcome="/recipes/formulation?faces-redirect=true">
								<f:param name="id" value="-1" />
								<f:param name="recipeId" value="#{recipeEditor.editedRecipe.id}" />
							</p:button>
						</ui:fragment>
					</p:panel>
				</p:outputPanel>
			</h:form>

			<p:growl sticky="false" globalOnly="true" life="2500" autoUpdate="true" />
		</ui:define>
	</ui:composition>
</body>
</html>